// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzvbfyzkkhamceegekdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6dmJmeXpra2hhbWNlZWdla2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzODYwMzksImV4cCI6MjA1Nzk2MjAzOX0.3KQ0zDOEmek2KzRr0BuRb2MPwXwsIx-sWqmrtxCQVpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);